# Generated by Django 5.2.4 on 2025-08-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Questionnaire',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ibs_answers', models.JSONField()),
                ('sus_answers', models.JSONField()),
                ('ueq_answers', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Pre_Questionnaire',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
                ('income', models.CharField(max_length=20)),
                ('shopping_preferences', models.JSONField()),
                ('live_shopping_frequency', models.CharField(max_length=20)),
                ('ibs_answers', models.JSONField()),
            ],
        ),
    ]
